services:
  spiewniki:
    image: quanosek/spiewniki:latest
    container_name: spiewniki
    restart: always
    env_file:
      - .env.local
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${HOST_PORT}:3000"
    volumes:
      - data:/app/node_modules

volumes:
  data:
